### ISSUE TITLE
Scripts Systems

### ISSUE THREAD

**Issue by barcelosrui** [RManPT/TOSEC#4]
In Commit on branch f7ecf2ddc3e334396ebebaee2b6b9f5b868739c9. The DatePicker not function.

**Comment by RManPT** [comment]
Não faz sentido criar um issue num branch de development ainda mais depois de ter informado toda a equipa para não fazerem pull dele precisamente porque estava no meio de experiênckas.

**Comment by barcelosrui** [comment]
Ok
